#!/usr/bin/env groovy
pipeline {
    agent {
        docker {
            image 'maven:3.8.6-jdk-11'
            label 'Built-In Node'
        }
    }

    stages {
        stage('Build') {
            steps {
                sh "mvn -version"
                sh "mvn clean install"
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
